version: '3'
services:
  app:
    container_name: dockernodeapp1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    

    volumes:
      - .:/app
    depends_on:
      - mongo
    environment:
      PORT: 3000
      DATABASE_URL: 'mongodb://app1:app1@mongo:27017/'
  mongo:
    container_name: dockermongoapp1
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: app1
      MONGO_INITDB_ROOT_PASSWORD: app1
   
    volumes:
      - expressapp2vol1:/data/db
volumes:
  expressapp2vol1:
